---
title: "Personality Prediction Presentation"
author: "Margaret Chien, Amber Liu, Daniel Njoo"
date: "12/9/2017"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Context
- Trump Tweets  
- Personality  

## Getting the Dataset
- https://www.kaggle.com/c/twitter-personality-prediction  
```{r message=F}
library(readxl)
library(tidyverse)
twitter_data <- read_excel("~/stat231/Projects/s231-final/shiny/twitter_data.xlsx")
```

## Data Wrangling
```{r}
library(tidyr)
library(dplyr)
twitterpersonality <- twitter_data[4:nrow(twitter_data),] %>% 
  sapply(., as.numeric) %>% 
  as.data.frame()
names(twitterpersonality) <- twitter_data[3, ]
twitterpersonality <- twitterpersonality %>%
  dplyr::select("openness", "conscientiousness", "extraversion", "agreeableness", "Neuroticism", "Machiavellianism", "narcissism", "psychopathy", "followers_count", "statuses_count", "favourites_count", "kloutscore", "PercentOrigTweets", "PercentRT", "PercentReplies")
```

## Visualizing the Data



## Clustering



## Shiny App



## Conclusions
